User.create(username: "user1", password: "useruser");
User.create(username: "user2", password: "useruser");
User.create(username: "admin", password: "adminadmin", admin: true);

Glossary.create(glossary_term: "murder", glossary_description: "Murder is the killing of another human being without justification or valid excuse, and it is especially the unlawful killing of another human being with malice aforethought.");
Glossary.create(glossary_term: "child murder", glossary_description: "Child murder or child homicide is the homicide of an individual under the age of 18.");
Glossary.create(glossary_term: "rape", glossary_description: "Rape is a type of sexual assault usually involving sexual intercourse or other forms of sexual penetration perpetrated against a person without that person's consent.");
Glossary.create(glossary_term: "assault", glossary_description: "An assault is carried out by a threat of bodily harm coupled with an apparent, present ability to cause the harm.");

Case.create(case_title: "Alih vs. CASTRO", case_number: "G.R. No. 64401", case_date: "June 23, 1987", case_content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras lacinia ligula quam. Quisque lobortis fermentum mi et facilisis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer condimentum ligula eros, quis malesuada felis finibus ut. Morbi ullamcorper, dolor nec lacinia egestas, tellus nulla euismod enim, vel tristique dui dui at felis. Fusce sit amet egestas erat. Fusce imperdiet fringilla laoreet. Donec finibus, erat eget pharetra pulvinar, ex mi efficitur ante, rutrum tincidunt risus augue sed ex. Sed scelerisque aliquam ante, at sollicitudin nisi porta ac. Donec gravida molestie mauris eget feugiat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.");
Case.create(case_title: "Republic vs. GST Phils Inc.", case_number: "GR. No. 190872", case_date: "October 17, 2013", case_content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras lacinia ligula quam. Quisque lobortis fermentum mi et facilisis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer condimentum ligula eros, quis malesuada felis finibus ut. Morbi ullamcorper, dolor nec lacinia egestas, tellus nulla euismod enim, vel tristique dui dui at felis. Fusce sit amet egestas erat. Fusce imperdiet fringilla laoreet. Donec finibus, erat eget pharetra pulvinar, ex mi efficitur ante, rutrum tincidunt risus augue sed ex. Sed scelerisque aliquam ante, at sollicitudin nisi porta ac. Donec gravida molestie mauris eget feugiat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.");
Case.create(case_title: "San Roque Power vs. CIR", case_number: "GR No. 180345", case_date: "November 25, 2009", case_content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras lacinia ligula quam. Quisque lobortis fermentum mi et facilisis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer condimentum ligula eros, quis malesuada felis finibus ut. Morbi ullamcorper, dolor nec lacinia egestas, tellus nulla euismod enim, vel tristique dui dui at felis. Fusce sit amet egestas erat. Fusce imperdiet fringilla laoreet. Donec finibus, erat eget pharetra pulvinar, ex mi efficitur ante, rutrum tincidunt risus augue sed ex. Sed scelerisque aliquam ante, at sollicitudin nisi porta ac. Donec gravida molestie mauris eget feugiat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.");

LegalForm.create(legal_form_title: "Deed of Donation", legal_form_content: "Deed of Donation: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras lacinia ligula quam. Quisque lobortis fermentum mi et facilisis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer condimentum ligula eros, quis malesuada felis finibus ut. Morbi ullamcorper, dolor nec lacinia egestas, tellus nulla euismod enim, vel tristique dui dui at felis. Fusce sit amet egestas erat. Fusce imperdiet fringilla laoreet. Donec finibus, erat eget pharetra pulvinar, ex mi efficitur ante, rutrum tincidunt risus augue sed ex. Sed scelerisque aliquam ante, at sollicitudin nisi porta ac. Donec gravida molestie mauris eget feugiat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.");
LegalForm.create(legal_form_title: "Deed of Sale", legal_form_content: "Deed of Sale: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras lacinia ligula quam. Quisque lobortis fermentum mi et facilisis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer condimentum ligula eros, quis malesuada felis finibus ut. Morbi ullamcorper, dolor nec lacinia egestas, tellus nulla euismod enim, vel tristique dui dui at felis. Fusce sit amet egestas erat. Fusce imperdiet fringilla laoreet. Donec finibus, erat eget pharetra pulvinar, ex mi efficitur ante, rutrum tincidunt risus augue sed ex. Sed scelerisque aliquam ante, at sollicitudin nisi porta ac. Donec gravida molestie mauris eget feugiat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.");
LegalForm.create(legal_form_title: "Contract", legal_form_content: "Contract: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras lacinia ligula quam. Quisque lobortis fermentum mi et facilisis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer condimentum ligula eros, quis malesuada felis finibus ut. Morbi ullamcorper, dolor nec lacinia egestas, tellus nulla euismod enim, vel tristique dui dui at felis. Fusce sit amet egestas erat. Fusce imperdiet fringilla laoreet. Donec finibus, erat eget pharetra pulvinar, ex mi efficitur ante, rutrum tincidunt risus augue sed ex. Sed scelerisque aliquam ante, at sollicitudin nisi porta ac. Donec gravida molestie mauris eget feugiat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.");